services:
    _defaults:
        autowire: true
        autoconfigure: true

    Awwar\SymfonyHttpEntityManager\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Resources}'
