services:
    _defaults:
        autowire: true
        autoconfigure: true

    Awwar\SymfonyHttpEntityManager\:
        resource: '../../*'
        exclude: '../../{DependencyInjection,Entity,Migrations,Tests,Resources}'

    Awwar\SymfonyHttpEntityManager\Service\Http\RelationMapper:
        autowire: false
        autoconfigure: false